name: Build seasonal dataset

on:
  workflow_dispatch:
  schedule:
    - cron: "21 3 * * *"  # daily at 03:21 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout farm-schema (for sample seasons file)
        uses: actions/checkout@v4
        with:
          repository: farm-companion/farm-schema
          path: farm-schema

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run seasonal pipeline (local provider)
        env:
          SEASON_PROVIDER: local
        run: ./seasons.sh

      # Notify farm-frontend to pull the latest seasons JSON immediately
      - name: Notify farm-frontend (repository_dispatch)
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.FRONTEND_DISPATCH_PAT }}
        run: |
          set -euo pipefail
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "FRONTEND_DISPATCH_PAT is missing"; exit 1
          fi
          echo 'Triggering repository_dispatch: seasons-updated'
          curl -fsSL -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${GH_TOKEN}" \
            https://api.github.com/repos/farm-companion/farm-frontend/dispatches \
            -d '{"event_type":"seasons-updated","client_payload":{"source_repo":"farm-pipeline","workflow":"seasons.yml"}}'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: seasons-uk
          path: dist/seasons.uk.json
          if-no-files-found: error
