name: Build seasonal dataset

on:
  workflow_dispatch:
  schedule:
    - cron: "21 3 * * *"  # daily at 03:21 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run seasonal pipeline (local provider)
        env:
          SEASON_PROVIDER: local
        run: ./seasons.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: seasons-uk
          path: dist/seasons.uk.json
          if-no-files-found: error
